CREATE TABLE shoe_inventory;


CREATE TABLE shoe_category (
  category_id	INT	NOT NULL AUTO_INCREMENT	PRIMARY KEY
, category_name	VARCHAR(12)	NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE size (
  size_id	INT	NOT NULL AUTO_INCREMENT	PRIMARY KEY
, size_num	VARCHAR(3)	NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE color (
  color_id	INT	NOT NULL AUTO_INCREMENT	PRIMARY KEY
, color_name	VARCHAR(12)	NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE shoe_style (
  style_id		INT	NOT NULL AUTO_INCREMENT	PRIMARY KEY
, style_name	VARCHAR(12)	NOT NULL
, wholesale_price FLOAT
, retail_price	FLOAT
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE shoe (
  shoe_id		INT	NOT NULL AUTO_INCREMENT	PRIMARY KEY
, category_id	INT	NOT NULL
, size_id		INT NOT NULL
, color_id		INT NOT NULL
, style_id		INT NOT NULL
, amt_in_stock	INT
) ENGINE=INNODB DEFAULT CHARSET=utf8;	

ALTER TABLE shoe 
ADD CONSTRAINT FOREIGN KEY (category_id)
	REFERENCES shoe_category(category_id)
	ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE shoe
ADD CONSTRAINT fk2_shoe FOREIGN KEY (size_id)
	REFERENCES size(size_id)
	ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE shoe
ADD CONSTRAINT FOREIGN KEY (color_id)
	REFERENCES color(color_id)
	ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE shoe
ADD CONSTRAINT fk4_shoe FOREIGN KEY (style_id)
	REFERENCES shoe_style(style_id)
	ON UPDATE CASCADE ON DELETE CASCADE;
